#!/bin/sh

echo "====================================================================="
echo "Here are some useful commands:"
echo "  ${akc_cmd}reset${akc_default} - reset MCU, ${akc_cmd}reset halt${akc_default} - reset and halt, ${akc_cmd}reset run${akc_default} - reset and run"
echo "  ${akc_cmd}make${akc_default} - run make without arguments"
echo "  ${akc_cmd}clean${akc_default} - run 'make clean'"
echo "  ${akc_cmd}write${akc_default} - write compiled production firmware into flash memory and reset"
echo "  ${akc_cmd}reg${akc_default} - list info about MCU registers (must be halted to see values)"
echo "  ${akc_cmd}halt${akc_default}, ${akc_cmd}resume${akc_default}, ${akc_cmd}step${akc_default} - obvious"
echo "  ${akc_cmd}mdw${akc_default}, ${akc_cmd}mdh${akc_default}, ${akc_cmd}mdb${akc_default} - Display data at addr"
echo "  ${akc_cmd}mww${akc_default}, ${akc_cmd}mwh${akc_default}, ${akc_cmd}mwb${akc_default} - Write data to addr"
echo "  ${akc_cmd}dump_image${akc_default} - dump memory into a file"
echo "  ${akc_cmd}help${akc_default} - help, ${akc_cmd}help <cmd>${akc_default} - help about a command"
echo ""
echo "Please also make sure that you have started 'connect-to-device-via-stlink' before you open ST-LINK console"
echo ""

telnet localhost 4444
